services:
  - type: web
    name: angnewa
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn angnewa.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: angnewa.onrender.com
      - key: SECRET_KEY
        value: "une-cle-secrete-solide-à-mettre-ici"
