# Generated by Django 5.2.4 on 2025-08-02 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('date_heure_depart', models.DateTimeField()),
                ('places_disponibles', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type_vehicule', models.CharField(choices=[('personnel', 'Personnel'), ('taxi', 'Taxi'), ('minibus', 'Minibus'), ('bus', 'Bus')], max_length=10)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
