# Generated by Django 5.2.4 on 2025-08-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='nombre_places',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='photo_voiture',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='experience_conduite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_permis',
            field=models.ImageField(blank=True, null=True, upload_to='permis_conduire/'),
        ),
    ]
