# Generated by Django 5.2.4 on 2025-08-04 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_utilisateur_nombre_places_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('date_heure_depart', models.DateTimeField()),
                ('places_totales', models.PositiveIntegerField()),
                ('places_reservees', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('avec_reservation', 'Avec réservation'), ('sans_reservation', 'Sans réservation')], max_length=20)),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques_trajets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
