# Generated by Django 5.2.4 on 2025-08-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_statistiquetrajet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='places_totales',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
