# Generated by Django 5.2.4 on 2025-08-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trajet_places_totales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='places_totales',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
