# Generated by Django 5.2.4 on 2025-08-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_trajet_places_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='photo_vehicule',
            field=models.ImageField(blank=True, null=True, upload_to='vehicules/'),
        ),
    ]
